# Generated by Django 3.2.6 on 2021-09-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligmacyweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
    ]
