# Generated by Django 3.2.7 on 2021-10-24 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligmacyweb', '0002_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligmacyweb.medicine')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligmacyweb.signup')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
